// bot/digest.js
// Codex Digest Agent - interprets emoji digests and weekly stats

/**
 * Codex Digest Agent
 * Role: Interpreter
 * Traits: executive-tone, emoji-native, math-ratio-logic, markdown-output
 */
class CodexDigestAgent {
  constructor() {
    this.agentId = "codex-digest-agent";
    this.role = "interpreter";
  }

  /**
   * Process emoji digest input and generate markdown summary
   * @param {Object} input - Input containing emoji-digest and weekly-stats
   * @returns {Object} - Output containing markdown-summary and action-recommendations
   */
  process(input) {
    const { emojiDigest = {}, weeklyStats = {} } = input;

    const summary = this.generateMarkdownSummary(emojiDigest, weeklyStats);
    const recommendations = this.generateActionRecommendations(weeklyStats);

    return {
      markdownSummary: summary,
      actionRecommendations: recommendations,
    };
  }

  /**
   * Generate a markdown summary from the emoji digest
   * @param {Object} emojiDigest - Emoji status mappings
   * @param {Object} weeklyStats - Weekly statistics
   * @returns {string} - Markdown formatted summary
   */
  generateMarkdownSummary(emojiDigest, weeklyStats) {
    const lines = [
      "# 📊 Weekly Codex Digest Report",
      "",
      "## Status Overview",
      "",
    ];

    // Process emoji digest
    if (Object.keys(emojiDigest).length > 0) {
      lines.push("| Emoji | Status | Count |");
      lines.push("|-------|--------|-------|");
      for (const [emoji, data] of Object.entries(emojiDigest)) {
        const status = data.status || "Unknown";
        const count = data.count || 0;
        lines.push(`| ${emoji} | ${status} | ${count} |`);
      }
      lines.push("");
    }

    // Process weekly stats
    if (Object.keys(weeklyStats).length > 0) {
      lines.push("## 📈 Weekly Statistics");
      lines.push("");
      for (const [key, value] of Object.entries(weeklyStats)) {
        lines.push(`- **${key}**: ${value}`);
      }
      lines.push("");
    }

    lines.push(`*Generated by ${this.agentId} at ${new Date().toISOString()}*`);

    return lines.join("\n");
  }

  /**
   * Generate action recommendations based on stats
   * @param {Object} weeklyStats - Weekly statistics
   * @returns {Array<string>} - List of recommended actions
   */
  generateActionRecommendations(weeklyStats) {
    const recommendations = [];

    const escalations = weeklyStats.escalations || 0;
    const blocked = weeklyStats.blocked || 0;
    const completionRate = weeklyStats.completionRate || 0;

    if (escalations > 10) {
      recommendations.push("🚨 High escalation count detected. Trigger planner-agent for resource reallocation.");
    }

    if (blocked > 5) {
      recommendations.push("⚠️ Multiple blocked items. Review blockers with team leads.");
    }

    if (completionRate < 70) {
      recommendations.push("📉 Completion rate below target. Consider sprint capacity adjustment.");
    }

    if (recommendations.length === 0) {
      recommendations.push("✅ All metrics within healthy ranges. Continue current workflow.");
    }

    return recommendations;
  }
}

// Export for use in other modules
module.exports = { CodexDigestAgent };

// CLI execution
if (require.main === module) {
  console.log("🤖 Codex Digest Agent Activated");

  const agent = new CodexDigestAgent();

  // Example input for testing
  const sampleInput = {
    emojiDigest: {
      "✅": { status: "Done", count: 15 },
      "🟡": { status: "In Progress", count: 8 },
      "❌": { status: "Blocked", count: 2 },
      "🛟": { status: "Escalation", count: 3 },
    },
    weeklyStats: {
      totalTasks: 30,
      completed: 15,
      inProgress: 8,
      blocked: 2,
      escalations: 3,
      completionRate: 50,
    },
  };

  const result = agent.process(sampleInput);
  console.log(result.markdownSummary);
  console.log("\n📋 Recommendations:");
  result.actionRecommendations.forEach((rec) => console.log(`  ${rec}`));
}
