import fs from 'fs'
import path from 'path'
import { Manifest } from './schema.js'
import { hasTrinity, getTrinityStatus } from './trinity.js'

type ServiceWithName = {
  name?: string
  repo: string
  env: string
  url: string
  health?: string
  depends: string[]
  notes?: string
}

/**
 * Normalizes services from either record or array format to a consistent array format
 */
function normalizeServices(services: Manifest['services']): ServiceWithName[] {
  if (Array.isArray(services)) {
    return services.map((svc) => svc as ServiceWithName)
  }
  return Object.entries(services || {}).map(([name, svc]) => ({
    name,
    ...svc,
  }))
}

/**
 * Extracts pack names from the manifest, handling both legacy packs array
 * and new categories structure
 */
function extractPackNames(manifest: Manifest): string[] {
  if (manifest.categories?.packs) {
    // Convert pack repo IDs to display names (e.g., "pack-education" -> "education")
    return manifest.categories.packs.map((packId) => {
      // Validate that it starts with pack- prefix
      if (packId.startsWith('pack-')) {
        return packId.replace(/^pack-/, '')
      }
      // Fall back to original ID if unexpected format
      console.warn(`Unexpected pack ID format: ${packId}. Expected 'pack-' prefix.`)
      return packId
    })
  }
  return manifest.packs || []
}

function matrix(manifest: Manifest) {
  const servicesArray = normalizeServices(manifest.services)

  const services = servicesArray.map((svc) => ({
    name: svc.name || svc.repo,
    repo: svc.repo,
    env: svc.env,
    url: svc.url,
    depends: svc.depends,
  }))

  return {
    version: manifest.version,
    repos: manifest.repos,
    ...(manifest.categories ? { categories: manifest.categories } : {}),
    ...(manifest.packs ? { packs: manifest.packs } : {}),
    environments: manifest.environments,
    services,
  }
  
  // Include Trinity data if available
  if (manifest.trinity) {
    matrixData.trinity = manifest.trinity
  }
  
  return matrixData
}

function envrc(manifest: Manifest) {
  const packNames = extractPackNames(manifest)
  const lines = [
    '# Generated by br-orchestrate render',
    `export ORCHESTRA_VERSION=${manifest.version}`,
    `export ORCHESTRA_PACKS=${packNames.join(',')}`,
    `export ORCHESTRA_ENVIRONMENTS=${Object.keys(manifest.environments).join(',')}`,
  ]
  return lines.join('\n') + '\n'
}

function readme(manifest: Manifest) {
  const servicesArray = normalizeServices(manifest.services)

  const rows = servicesArray
    .map((svc) => {
      const name = svc.name || svc.repo
      const depends = svc.depends?.length ? svc.depends.join(', ') : '—'
      const health = svc.health ?? '—'
      return `| ${name} | ${svc.env} | ${svc.repo} | ${svc.url} | ${health} | ${depends} |`
    })
    .join('\n')

  const edges = servicesArray.flatMap((svc) => {
    const name = svc.name || svc.repo
    return (svc.depends || []).map((dep) => `${name} --> ${dep}`)
  })

  const mermaid = ['```mermaid', 'graph LR', ...(edges.length ? edges : ['%% no deps']), '```'].join(
    '\n'
  )
  let header: string
  try {
    header = fs.readFileSync(path.join(process.cwd(), 'README.stub.md'), 'utf-8')
  } catch (err) {
    header =
      '# Service Overview\n\n> README.stub.md not found or unreadable. Please provide a stub file for a custom header.\n'
    console.warn('Warning: README.stub.md not found or unreadable:', err)
  }
  const table = `| Service | Env | Repo | URL | Health | Depends |\n| --- | --- | --- | --- | --- | --- |\n${rows}`
  const packs = manifest.packs.length
    ? manifest.packs.map((pack) => `- ${pack}`).join('\n')
    : '_No packs defined._'
  const environmentsRows = Object.entries(manifest.environments)
    .map(([name, env]) => `| ${name} | ${env.domain_root} |`)
    .join('\n')
  const environmentsTable = `| Environment | Domain Root |\n| --- | --- |\n${environmentsRows}`
  return [
    header.trim(),
    '',
    '## Service Matrix',
    table,
    '',
    '## Packs',
    packs,
    '',
    '## Environments',
    environmentsTable,
    '',
    '## Topology',
    mermaid,
    '',
  ].join('\n')
}

export function render(manifest: Manifest, cwd = process.cwd()) {
  const matrixPath = path.join(cwd, '.matrix.json')
  const envrcPath = path.join(cwd, '.envrc')
  const readmePath = path.join(cwd, 'README.md')
  fs.writeFileSync(matrixPath, JSON.stringify(matrix(manifest), null, 2))
  fs.writeFileSync(envrcPath, envrc(manifest))
  fs.writeFileSync(readmePath, readme(manifest))
}
