import fs from 'fs'
import path from 'path'
import { Manifest } from './schema.js'

type ServiceWithName = {
  name?: string
  repo: string
  env: string
  url: string
  health?: string
  depends: string[]
  notes?: string
}

function matrix(manifest: Manifest) {
  // Normalize services to array format
  const servicesArray: ServiceWithName[] = Array.isArray(manifest.services)
    ? manifest.services.map((svc) => svc as ServiceWithName)
    : Object.entries(manifest.services || {}).map(([name, svc]) => ({
        name,
        ...svc,
      }))

  const services = servicesArray.map((svc) => ({
    name: svc.name || svc.repo,
    repo: svc.repo,
    env: svc.env,
    url: svc.url,
    depends: svc.depends,
  }))

  return {
    version: manifest.version,
    repos: manifest.repos,
    ...(manifest.categories ? { categories: manifest.categories } : {}),
    ...(manifest.packs ? { packs: manifest.packs } : {}),
    environments: manifest.environments,
    services,
  }
}

function envrc(manifest: Manifest) {
  // Extract pack names from categories.packs if available, falling back to manifest.packs
  let packNames: string[] = []
  if (manifest.categories?.packs) {
    // Convert pack repo IDs to display names (e.g., "pack-education" -> "education")
    packNames = manifest.categories.packs.map((packId) => packId.replace(/^pack-/, ''))
  } else if (manifest.packs) {
    packNames = manifest.packs
  }
  
  const lines = [
    '# Generated by br-orchestrate render',
    `export ORCHESTRA_VERSION=${manifest.version}`,
    `export ORCHESTRA_PACKS=${packNames.join(',')}`,
    `export ORCHESTRA_ENVIRONMENTS=${Object.keys(manifest.environments).join(',')}`,
  ]
  return lines.join('\n') + '\n'
}

function readme(manifest: Manifest) {
  // Normalize services to array format
  const servicesArray: ServiceWithName[] = Array.isArray(manifest.services)
    ? manifest.services.map((svc) => svc as ServiceWithName)
    : Object.entries(manifest.services || {}).map(([name, svc]) => ({
        name,
        ...svc,
      }))

  const rows = servicesArray
    .map((svc) => {
      const name = svc.name || svc.repo
      const depends = svc.depends?.length ? svc.depends.join(', ') : '—'
      const health = svc.health ?? '—'
      return `| ${name} | ${svc.env} | ${svc.repo} | ${svc.url} | ${health} | ${depends} |`
    })
    .join('\n')

  const edges = servicesArray.flatMap((svc) => {
    const name = svc.name || svc.repo
    return (svc.depends || []).map((dep) => `${name} --> ${dep}`)
  })

  const mermaid = ['```mermaid', 'graph LR', ...(edges.length ? edges : ['%% no deps']), '```'].join(
    '\n'
  )
  let header: string
  try {
    header = fs.readFileSync(path.join(process.cwd(), 'README.stub.md'), 'utf-8')
  } catch (err) {
    header =
      '# Service Overview\n\n> README.stub.md not found or unreadable. Please provide a stub file for a custom header.\n'
    console.warn('Warning: README.stub.md not found or unreadable:', err)
  }
  const table = `| Service | Env | Repo | URL | Health | Depends |\n| --- | --- | --- | --- | --- | --- |\n${rows}`
  return [header.trim(), '', '## Service Matrix', table, '', '## Topology', mermaid, ''].join('\n')
}

export function render(manifest: Manifest, cwd = process.cwd()) {
  const matrixPath = path.join(cwd, '.matrix.json')
  const envrcPath = path.join(cwd, '.envrc')
  const readmePath = path.join(cwd, 'README.md')
  fs.writeFileSync(matrixPath, JSON.stringify(matrix(manifest), null, 2))
  fs.writeFileSync(envrcPath, envrc(manifest))
  fs.writeFileSync(readmePath, readme(manifest))
}
